### ISSUE TITLE
Reservation model

### ISSUE THREAD

**Issue by sainingo** [medi-book/medibook-api#10]
Hello @deyemiobaa @OybekKayumov,
In our reservation model, I think we forgot to add the duration for the appointment and total cost (Duration is hour-long a user wants to book a doctor, let's say 2 hours book and @hr is 50usd we need to get that total as well).
Reservation model:
- appointment date (date)
- duration
- total

**Comment by deyemiobaa** [comment]
Hello @sainingo. That's a very good point. Thanks for raising that up. Can you add the changes to your migrations? We'll get the updates when we merge.

Also, I'll appreciate if you could generate an ERD for our database and add it to the readme. Just to help us visualize our relations.

**Comment by sainingo** [comment]
Ok @deyemiobaa
