### ISSUE TITLE
Kanban Board Setup

### ISSUE THREAD

**Issue by deyemiobaa** [medi-book/medibook-api#8]
Hi reviewer. We are a team of 5 @sainingo @OybekKayumov @IfzaRasool @AnicetFantomas @deyemiobaa 

Here is the link to the [project board](https://github.com/orgs/medi-book/projects/1)

![image](https://user-images.githubusercontent.com/55185309/185373522-2a05a241-d940-4859-80ae-7d44e88b9139.png)

**Comment by MuriloRoque** [comment]
Hi @deyemiobaa,

In my opinion, your project is complete!

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
